---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

```{r}
rm(list=ls())
library(corrplot)
df <- read.csv(file="./volatility.csv")
head(df)


AAPL.PVol = df$AAPL.PVol
GOOG.PVol = df$GOOG.PVol
AMZN.PVol = df$AMZN.PVol
GSPC.PVol = df$GSPC.PVol
VIX.Close = df$VIX.Close
AAPL.Close = df$AAPL.Close
VXAPLCLS = df$VXAPLCLS
VXAZNCLS = df$VXAZNCLS
VXGOGCLS = df$VXGOGCLS 
GOOG.Close = df$GOOG.Close
AMZN.Close = df$AMZN.Close
GSPC.Close = df$GSPC.Close 
Date = df$Date
AAPL.Ret = df$AAPL.Ret
AMZN.Ret = df$AMZN.Ret
GOOG.Ret = df$GOOG.Ret
GSPC.Ret = df$GSPC.Ret
AAPL.Vol = df$AAPL.Vol
```

```{r}
library(dplyr)
library(ggplot2)
```

```{r}
m = cov(cbind(AAPL.PVol,GOOG.PVol,AMZN.PVol,GSPC.PVol, 
          VIX.Close, AAPL.Close, VXAPLCLS, VXAZNCLS, 
          VXGOGCLS, GOOG.Close, AMZN.Close, GSPC.Close,
          Date, AAPL.Ret, AMZN.Ret, GOOG.Ret, GSPC.Ret, AAPL.Vol))
ans <- data.frame(row=rownames(m)[row(m)], col=colnames(m)[col(m)], corr=c(m)) %>% filter(col == 'AAPL.Vol')
write.csv(ans, "./cov.csv", row.names = FALSE)
ans
```

## **Looking at correlation between variables**

```{r}
corr_matrix = cbind(AAPL.PVol,GOOG.PVol,AMZN.PVol,GSPC.PVol, 
          VIX.Close, AAPL.Close, VXAPLCLS, VXAZNCLS, 
          VXGOGCLS, GOOG.Close, AMZN.Close, GSPC.Close,
          Date, AAPL.Ret, AMZN.Ret, GOOG.Ret, GSPC.Ret, AAPL.Vol)
corr_matrix = cor(corr_matrix, method = c("pearson"))
corrplot(corr_matrix, method="color")
```

## **Descriptive Statistics:**

```{r}
# Getting descriptive statistics
summary(AAPL.PVol)
summary(GOOG.PVol)
summary(AMZN.PVol)
summary(GSPC.PVol)
```

```{r}
summary(VXAPLCLS) 
summary(VXAZNCLS)
summary(VXGOGCLS) 
```

```{r}
summary(VIX.Close)
summary(AAPL.Close)
summary(GOOG.Close) 
summary(AMZN.Close)
summary(GSPC.Close)
```

```{r}
summary(AAPL.Ret) 
summary(AMZN.Ret) 
summary(GOOG.Ret) 
summary(GSPC.Ret) 
```

```{r}
summary(AAPL.Vol)
```

## **Looking at Apple.Volatility vs Apple.PVolatility**

```{r}
# Fitting a simple linear regression model for AAPL.Vol and 
# each independent variable, and checking the five key
# assumptions: Linear relationship, Multivariate normality, 
# No multicollinearity, No auto-correlation and Homoscedasticity, 
# the assumptions of the simple linear regression are acceptable.
summary(lm(AAPL.Vol~AAPL.PVol))
```

```{r}
plot(AAPL.PVol,AAPL.Vol)
abline(lm(AAPL.Vol~AAPL.PVol))
```

```{r}
plot(lm(AAPL.Vol ~ AAPL.PVol))
```

## **Looking at Apple.Volatility vs Google.PVolatility**

```{r}
summary(lm(AAPL.Vol~GOOG.PVol))
```

```{r}
plot(GOOG.PVol, AAPL.Vol)
abline(lm(AAPL.Vol~GOOG.PVol))
```

```{r}
plot(lm(AAPL.Vol~GOOG.PVol))
```

## **Looking at Apple.Volatility vs Amazon.PVolatility**

```{r}
summary(lm(AAPL.Vol~AMZN.PVol))
```

```{r}
plot(AMZN.PVol,AAPL.Vol)
abline(lm(AAPL.Vol~AMZN.PVol))
```

```{r}
plot(lm(AAPL.Vol~AMZN.PVol))
```

## **Looking at Apple.Volatility vs GSPC.PVol**

```{r}
summary(lm(AAPL.Vol~GSPC.PVol))
```

```{r}
plot(GSPC.PVol, AAPL.Vol)
abline(lm(AAPL.Vol~GSPC.PVol))
```

```{r}
plot(lm(AAPL.Vol~GSPC.PVol))
```

Looking just between scatterplot

```{r}

##predicted volatilities
plot(AAPL.Vol~AAPL.PVol)
plot(AAPL.Vol~GOOG.PVol)
plot(AAPL.Vol~AMZN.PVol)
plot(AAPL.Vol~GSPC.PVol)


##residuals
##predictied volatilities
plot(AAPL.PVol, resid(lm(AAPL.Vol~AAPL.PVol)))
plot(GOOG.PVol, lm(AAPL.Vol~GOOG.PVol)$residuals)
plot(AMZN.PVol, lm(AAPL.Vol~AMZN.PVol)$residuals)
plot(GSPC.PVol, lm(AAPL.Vol~GSPC.PVol)$residuals)
```

```{r}
##closing prices
plot(AAPL.Vol~AAPL.Close)
plot(AAPL.Vol~GOOG.Close)
plot(AAPL.Vol~AMZN.Close)
plot(AAPL.Vol~GSPC.Close)

#closing
plot(AAPL.Close, lm(AAPL.Vol~AAPL.Close)$residuals)
plot(GOOG.Close, lm(AAPL.Vol~GOOG.Close)$residuals)
plot(AMZN.Close, lm(AAPL.Vol~AMZN.Close)$residuals)
plot(GSPC.Close, lm(AAPL.Vol~GSPC.Close)$residuals)
```

```{r}
##returns
plot(AAPL.Vol~AAPL.Ret)
plot(AAPL.Vol~GOOG.Ret)
plot(AAPL.Vol~AMZN.Ret)
plot(AAPL.Vol~GSPC.Ret)

#returns
plot(AAPL.Ret, lm(AAPL.Vol~AAPL.Ret)$residuals)
plot(GOOG.Ret, lm(AAPL.Vol~GOOG.Ret)$residuals)
plot(AMZN.Ret, lm(AAPL.Vol~AMZN.Ret)$residuals)
plot(GSPC.Ret, lm(AAPL.Vol~GSPC.Ret)$residuals)
```

```{r}
##VIX
plot(AAPL.Vol~VXAPLCLS)
plot(AAPL.Vol~VXGOGCLS)
plot(AAPL.Vol~VXAZNCLS)
plot(AAPL.Vol~VIX.Close)

#VIX
plot(VXAPLCLS, lm(AAPL.Vol~VXAPLCLS)$residuals)
plot(VXGOGCLS, lm(AAPL.Vol~VXGOGCLS)$residuals)
plot(VXAZNCLS, lm(AAPL.Vol~VXAZNCLS)$residuals)
plot(VIX.Close, lm(AAPL.Vol~VIX.Close)$residuals)
```
